### ISSUE TITLE
Prevent new accounts starting with ibc.

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/telos.contracts#38]
## Overview
We want to block any account other than `eosio` to protect inter-blockchain communication. The goal of this is to block any account to be created starting with `ibc.` unless its `eosio`. 

## Acceptance Criteria
Add the following code to the `newaccount` action
```
if (!has_auth(_self)){
      check(nm.to_string().find("ibc.", 0, 4) != 0, "only eosio can create names that start with 'ibc.'");
}
```
## Acceptance criteria
- Make the changes into dev
- DO NOT deploy it

## Task
- Make sure the current repository is up to date
- Create a PR to dev

**Comment by guilledk** [comment]
Closed by #39
